name: Build Arsenal
on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y python3-dev build-essential libffi-dev git
      
      - name: Install Briefcase
        run: pip install briefcase

      - name: Build App
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            # Для AppImage флаг нужен
            briefcase package linux appimage --no-input --no-docker
            # Для System (DEB) флаг НЕ нужен
            briefcase package linux system --no-input
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            briefcase package windows app --no-input
          else
            briefcase package macOS app --no-input --adhoc-sign
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arsenal-dist-${{ matrix.os }}
          path: dist/*
