name: Build Arsenal
on: [push]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install System Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-pip build-essential libffi-dev git
      
      - name: Install Briefcase
        run: |
          # Используем флаг для обхода ограничений системы
          python3 -m pip install briefcase --break-system-packages

      - name: Build App
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            # Собираем Linux
            python3 -m briefcase package linux appimage --no-input --no-docker
            python3 -m briefcase package linux system --no-input
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Windows (здесь флаг не нужен, но briefcase вызывается так же)
            briefcase package windows app --no-input
          else
            # macOS (тоже добавляем --break-system-packages если нужно, 
            # но briefcase обычно справляется сам)
            python3 -m briefcase package macOS app --no-input --adhoc-sign
          fi
        shell: bash


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: arsenal-dist-${{ matrix.os }}
          path: dist/*
